#!/usr/bin/env python3
"""Generate probes.h: map TD_* macros to the Verilator-flattened member
names of the signals the trace-diff observes (GCR byte stream and track
DMA writes per drive). Reads the verilated root header."""

import re
import sys

hdr = open(sys.argv[1]).read()
members = re.findall(r"[&>]\s*(\w+)\s*;|VL_\w+\((\w+),", hdr)
names = set(m[0] or m[1] for m in members)
# more robust: grab every identifier that looks like a flattened path
names |= set(re.findall(r"\b(c1541__DOT__\w+)\b", hdr))


def find(*patterns):
    for n in sorted(names):
        if all(re.search(p, n) for p in patterns):
            return n
    return None


defs = []
missing = []
for d in (0, 1):
    drv = rf"BRA__{d}__KET____DOT__c1541_drv"
    m = {
        f"TD_BYTE_N_{d}":  find(r"c1541__DOT__drives", drv, r"dgcr_byte_n$"),
        f"TD_DOUT_{d}":    find(r"c1541__DOT__drives", drv, r"dgcr_do$"),
        f"TD_DMAWR_{d}":   find(r"c1541__DOT__drives", drv, r"__DOT__dma_buff_wr$"),
        f"TD_DMAADDR_{d}": find(r"c1541__DOT__drives", drv, r"__DOT__dma_buff_addr$"),
        f"TD_DMADATA_{d}": find(r"c1541__DOT__drives", drv, r"__DOT__dma_buff_dout$"),
    }
    for k, v in m.items():
        if v:
            defs.append(f"#define {k} (dut->tracediff_top->iec_drive->{v})")
        else:
            missing.append(k)
            defs.append(f"#define {k} 0  /* NOT FOUND */")

print("// generated by gen_probes.py - do not edit")
for line in defs:
    print(line)

if missing:
    sys.stderr.write("gen_probes: NOT FOUND: " + " ".join(missing) + "\n")
    critical = [m for m in missing if "BYTE_N" in m or "DOUT" in m]
    sys.exit(1 if critical else 0)
